- hosts: 10.8.20.116
  become: true
  roles:
  - role: entercloudsuite.haproxy
    haproxy_user: haproxyuser
    haproxy_pass: haproxypass
    haproxy_conf: |
      listen web
          mode http
          bind *:80
          default-server port 80
          server web-0 1.1.1.1:80 check
