---
- hosts: 10.8.24.10
  become: true
  roles:
  - dns
# - hosts: 10.8.24.11
#   become: true
#   roles:
#   - dhcp
# # - hosts: 10.8.24.114
# #   become: true
# #   roles:
# #   - role: ansible-apache2
# #   - role: ansible-mariadb-mysql
# #   - role: ansible-powerdns  
# - hosts: 10.8.24.12
#   become: true
#   roles:
#   - role: entercloudsuite.haproxy
#     haproxy_user: haproxyuser
#     haproxy_pass: haproxypass
# - hosts: 10.8.24.13
#   become: true
#   roles:
#   - web
