apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slave
parameters:
  datastore: VMFS02
  diskformat: thin
provisioner: kubernetes.io/vsphere-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
