apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  name: confluence
  namespace: confluence
spec:
  port:
    targetPort: 8090
  subdomain: ""
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: confluence 
    weight: 100
  wildcardPolicy: None
