kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    "helm.sh/resource-policy": kepp
  name: data-{{ template "stolon.fullname" . }}-keeper-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote  }}
  {{- if .Values.persistence.storageClassName1 }}
    {{- if (eq "-" .Values.persistence.storageClassName1) }}
  storageClassName: ""
    {{- else }}
  storageClassName: "{{ .Values.persistence.storageClassName1 }}"
    {{- end }}
  {{- end }}
  volumeMode: Filesystem