apiVersion: v1
kind: Pod
metadata:
  name: runner
spec:
  containers:
  - env:
    image: docker.io/elts/gitlab-runner:ubuntu18
    name: runner
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 100;done"]
