apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  name: CreatePods
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods/finalizers
  verbs:
  - update 
