apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  name: web
  namespace: jenkins
spec:
  port:
    targetPort: 8080
  subdomain: ""
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jenkins 
    weight: 100
  wildcardPolicy: None
