dependencies:
- name: postgresql
  version: 7.0.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: rabbitmq-ha
  version: 1.38.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq-ha.enabled
- name: rabbitmq
  version: 6.16.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq.enabled
